### ISSUE TITLE
Efficient medicine search algorithm

### ISSUE THREAD

**Issue by tapish2000** [tapish2000/medconnect-web#13]
Multiple medicines will be searched and you have to design the algorithm to show the shops in which they are available.
You can refer to this algorithm. Make something related...
### Algorithm:
Searching based on multiple medicine algorithm - 
* Show all such shops which have all the searched medicines in it.
* Set `minDist` = minimum distance of the above-listed shops
* Search all those shops which do not have these medicines altogether
* Show the shops which have a total distance of these shops (if there are two such shops which have these medicines divided, then the total distance will be the distance between nearest shop and home + distance between both shops) less than `minDist`.
* Perform the above step for printing 10 such shops for now and when clicked on Show More, perform for 10 more such shops.

**Comment by chirag2706** [comment]
i will be designing this algorithm.Please,assign me this issue.
