### ISSUE TITLE
Bug fixing

### ISSUE THREAD

**Issue by tapish2000** [tapish2000/medconnect-web#32]
Following issues are to be solved:

- [x] Home page top brands just logo, no card text @rohit-cs18b029 
- [x] Home page medicine cards to be linked correctly to the details page
- [x] All branded medicine pages, top brands - logo to be shown not text @shobhi1310 
- [x] Search Area logic implementation
- [x] Search Button to be added @shobhi1310 
- [x] List of tags for the search component to be changed to medicine names @shobhi1310 
- [x] Remove breadcrumbs @rohit-cs18b029 
- [x] Populate database for Ayurvedic and Allopathic-generic type medicines @chirag2706 
- [x] Going to the homepage on clicking the logo and name on the navbar @shobhi1310 
- [x] In `/shoplist` page, add `Details` button on each card and add `Add to Cart` button on each shop card. @shobhi1310 
- [x] Some irrelevant medicines are added in the DB, remove them.
- [x] Remove the informal words like:
![image](https://user-images.githubusercontent.com/44476667/97862339-26ff5900-1d2b-11eb-8a17-1e0fc2c06588.png)

**Comment by shobhi1310** [comment]
For carousel I have checked removing arrows is very easy, like it is done through 1 line of code in CSS but putting a conditional check is an unnecessary overhead, and I checked other websites also, it does not really matter much if the arrows exist even if the number of items is much, user understands and accepts the fact.

**So remove the last issue from the list only.**

**Comment by rohit-cs18b029** [comment]
change the card in daily use category in home page

**Comment by shobhi1310** [comment]
I have checked the search based tagging system and the tags get stored into the state of the search component which can be sent on clicking search, so no code change is required.

**So, you can unassign me from the search area logic implementation and assign @chirag2706**

**Comment by shobhi1310** [comment]
@chirag2706  has done the database updation as well, check mark the 3rd last issue as well.
