### ISSUE TITLE
Carousel in Home page for news/suggestions

### ISSUE THREAD

**Issue by shobhi1310** [tapish2000/medconnect-web#4]
create a dynamic carousel sort of feature which shows all the recent news related to field of medicine or yoga, etc. which is to be present in home page.

**Comment by rohit-cs18b029** [comment]
please assign this issue to me

**Comment by tapish2000** [comment]
@rohit-cs18b029 Sorry to mention late, but you should create a folder named `components` inside `src` and then put the component you make in that.
